# Generated by Django 5.0.4 on 2024-04-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Result",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("result", models.IntegerField()),
                ("detail", models.CharField(max_length=1000)),
                ("comment", models.CharField(max_length=1000)),
                ("save_path", models.CharField(max_length=1000)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
